添加了拿到新电脑后跑起llvm的过程
lazyparser/survival-manual-for-interns pull request #6
Opened 2020-05-10 04:50 UTC by pz9115

2020-05-10 07:09 UTC, lazyparser requested changes
nice try

有关 git 和 bash 的使用，看下评论。有可能是错误的。

另外，一开始的文档更新，也看下。

2020-05-10 07:09 UTC, lazyparser commented on tips.rst
> -====================================================
这里为何删除了？

2020-05-10 07:09 UTC, lazyparser commented on tips.rst
> +    	deb http://mirrors.aliyun.com/ubuntu/ bionic main restricted universe multiverse
这里不要列举。

既然是已经用了 vim ，那么就直接

`:%s:cn.archive.ubuntu:mirrors.aliyun:g`

就可以搞定的。试试看。

2020-05-10 07:09 UTC, lazyparser commented on tips.rst
> +    $ git init
这是完全错误的啊。这两行命令的理解，你是不是搞错了？

2020-05-10 07:09 UTC, lazyparser commented on tips.rst
> +	make -j4
date 是可以的。

不过一般我们是直接用 `time` 命令的

`time make -j 4`

最后就会输出的。

2020-05-10 16:00 UTC, pz9115 commented on tips.rst
> -====================================================
这里显示格式有问题，修复了一下

2020-05-10 16:01 UTC, pz9115 commented on tips.rst
> +    	deb http://mirrors.aliyun.com/ubuntu/ bionic main restricted universe multiverse
成功查找替换

2020-05-10 16:01 UTC, pz9115 commented on tips.rst
> +    $ git init
之前搞错了，老想init一下

2020-05-10 16:01 UTC, pz9115 commented on tips.rst
> +	make -j4
ok

2020-05-11 07:51 UTC, lazyparser requested changes
better
继续按照说明修改下。

尤其是一开始的小标题，保留。

2020-05-11 07:51 UTC, lazyparser commented on tips.rst
> -====================================================
这里应该是要求作为一个小标题的。
修复的话可以在 === 之后加入一个回车换行。

2020-05-11 07:51 UTC, lazyparser commented on tips.rst
> +在使用Word编辑文档时，将常用的术语加入“字典”，这样做能够方便编辑器发挥其拼写检查功能。
同样的，这里同样是一个小标题。
改成小标题的形式？

2020-05-11 07:51 UTC, lazyparser commented on tips.rst
> +1. 进入系统后安装wsl/wsl2（默认ubuntu18.04），安装方法可以参考这篇官方文档https://docs.microsoft.com/zh-cn/windows/wsl/install-win10
参考《实习生存指南》tips

这里URL违反了规则，前后没有加入空格，导致点击或显示可能很糟糕。

2020-05-11 07:51 UTC, lazyparser commented on tips.rst
> +2. 从开始菜单进入安装好的ubuntu系统中，进入/etc/apt更换软件源为国内源(以阿里云软件源为例),并更新软件列表:
`/etc/apt/` 这样的目录，用代码格式，前后空格。

2020-05-11 07:51 UTC, lazyparser commented on tips.rst
> +    ..
这里的 `..` 去掉，改成用注释说明的形式。
如果是对vim不熟悉的人，会不知道下面的代码什么意思。需要进行说明。

2020-05-11 07:51 UTC, lazyparser commented on tips.rst
> +7. 编写一个简单的shell来编译llvm，并记录你的编译用时(已知鲲鹏服务器编译只用了9分钟，变相跑分！！)
已知鲲鹏服务器编译只用了9分钟，变相跑分！！)

这里删除掉。跟本手册无关。

2020-05-11 09:24 UTC, lazyparser approved these changes

2020-05-11 09:24 UTC, merged

2020-05-11 09:24 UTC, lazyparser commented
good job